swagger: '2.0'

info:
  version: "1.0.0"
  title: Commons Service
  description: Commons services APIs - to create, update and search Commons. 
  contact:
    name: Manikanta P T
    email: info@egovernments.org
  
basePath: "/egov-commons/v110"
x-common-path: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/financials/egov-commons/contracts/v1-0-0.yml'
x-api-id: 'org.egov.infra.commons'
swagger: '2.0'

info:
  version: "1.0.0"
  title: Commons Service
  description: Commons services APIs - to create, update and search Commons. 
  contact:
    name: Manikanta P T
    email: info@egovernments.org
  
basePath: "/egov-commons/v110"
x-common-path: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/financials/egov-commons/contracts/v1-0-0.yml'
x-api-id: 'org.egov.infra.commons'
swagger: '2.0'

info:
  version: "1.0.0"
  title: Commons Service
  description: Commons services APIs - to create, update and search Commons. 
  contact:
    name: Manikanta P T
    email: info@egovernments.org
  
basePath: "/egov-commons/v110"
x-common-path: 'https://raw.githubusercontent.com/egovernments/egov-services/master/docs/financials/egov-commons/contracts/v1-0-0.yml'
x-api-id: 'org.egov.infra.commons'
